# get version from setup.py
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: aspired
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install . --no-deps -vv
  python:
    - 3.7
    - 3.8
    - 3.9
    - 3.10
    - 3.11
  target_platform: osx-64, win-64, linux-64
  target_subdir: "{platform}-{arch}"

requirements:
  build:
    - python>=3.7
    - setuptools
  run:
    {% for req in data.get('install_requires', []) %}
      - {{ req }}
    {% endfor %}

test:
 imports:
   - aspired

about:
  home: https://github.com/cylammarco/SpectResC
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: SpectResC is a Python module based on the original work SpectRes, written with C Extension to efficiently resample spectra and associated uncertainties onto an arbitrary wavelength grid.
  summary: SpectResC is an implementation of SpectRes with C-extension in Python.