name: Build and Test

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26, ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: macos-latest
            env: CC="clang" CXX="clang++"
          - os: ubuntu-latest
            env: CC="gcc" CXX="g++"
          - os: windows-latest
            env: CC="mingw64-gcc" CXX="mingw64-g++"

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
          python -m pip install --upgrade flake8 pytest pytest-cov coverage spectres
          python -m pip install --upgrade -r requirements.txt
          python -m pip install -e .
    - name: Test with pytest
      run: |
        coverage run -m pytest --disable-warnings -p no:warnings test
    - name: Coveralls
      if: startsWith(matrix.os, 'ubuntu') && endsWith(matrix.python-version, '3.14')
      uses: coverallsapp/github-action@v2
